//! Handing nxm:// links from the browser handler process to a running lmm.
//!
//! When the user clicks "Mod Manager Download", the desktop launches a fresh
//! `lmm nxm <url>` process (see [`crate::xdg`]). That process must get the
//! link to wherever it will actually be handled:
//!
//! - **An lmm shell is running** — it listens on a unix socket; the handler
//!   connects, sends the link, waits for a one-line acknowledgement, exits.
//! - **No instance is running** — the handler writes the link to a spool
//!   directory; the next lmm start drains the spool and queues the requests.
//!
//! Protocol (deliberately trivial): one `NXM <url>\n` line in, one
//! `OK <text>\n` or `ERR <text>\n` line back. Lines are length-capped.
//! Everything read from the socket is untrusted — any local process can
//! connect — so the receiver re-validates the link before acting on it, and
//! the reply text is generated by us, never echoed input.
//!
//! The socket lives in `$XDG_RUNTIME_DIR` (per-user, mode 0700, tmpfs) when
//! available, otherwise in the data dir. Its name embeds a hash of the data
//! dir so two lmm setups (e.g. tests with `--data-dir`) never cross-talk.

use std::io::{BufRead, BufReader, Read, Write};
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::os::unix::net::{UnixListener, UnixStream};
use std::path::{Path, PathBuf};
use std::time::Duration;

use lmm_core::config::DataPaths;
use sha2::{Digest, Sha256};

use crate::{Error, Result};

/// Longest line we accept over the socket: "NXM " + a max-length link.
const MAX_LINE: u64 = 4096;
const IO_TIMEOUT: Duration = Duration::from_secs(5);
/// Ignore spool files larger than this — a real request is one short line.
const MAX_SPOOL_FILE: u64 = 8192;

/// Where the listener socket for `paths`' data dir lives.
pub fn socket_path(paths: &DataPaths) -> PathBuf {
    // Hash the canonical-ish data dir into the name: unique per setup, and
    // short enough for the 108-byte sun_path limit when under /run/user.
    let digest = Sha256::digest(paths.data_dir.as_os_str().as_encoded_bytes());
    let tag: String = digest.iter().take(4).map(|b| format!("{b:02x}")).collect();
    let name = format!("lmm-{tag}.sock");
    match std::env::var_os("XDG_RUNTIME_DIR") {
        Some(dir) if !dir.is_empty() => PathBuf::from(dir).join(name),
        _ => paths.data_dir.join(name),
    }
}

/// Outcome of trying to hand a link to a running instance.
pub enum Delivery {
    /// A running lmm accepted the link; its reply text is included.
    Accepted(String),
    /// A running lmm rejected the link (e.g. it failed validation there).
    Rejected(String),
    /// Nobody is listening.
    NotRunning,
}

/// Try to deliver `raw_link` to a running lmm instance over the socket.
pub fn send_to_running(paths: &DataPaths, raw_link: &str) -> Result<Delivery> {
    let path = socket_path(paths);
    let mut stream = match UnixStream::connect(&path) {
        Ok(s) => s,
        // NotFound: no socket file; ConnectionRefused: stale socket file.
        Err(e)
            if matches!(
                e.kind(),
                std::io::ErrorKind::NotFound | std::io::ErrorKind::ConnectionRefused
            ) =>
        {
            return Ok(Delivery::NotRunning);
        }
        Err(e) => return Err(Error::io(&path, e)),
    };
    stream
        .set_read_timeout(Some(IO_TIMEOUT))
        .and_then(|()| stream.set_write_timeout(Some(IO_TIMEOUT)))
        .map_err(|e| Error::io(&path, e))?;

    stream
        .write_all(format!("NXM {raw_link}\n").as_bytes())
        .map_err(|e| Error::io(&path, e))?;

    let mut reply = String::new();
    BufReader::new(&stream)
        .take(MAX_LINE)
        .read_line(&mut reply)
        .map_err(|e| Error::io(&path, e))?;
    let reply = reply.trim();
    match reply.split_once(' ') {
        Some(("OK", text)) => Ok(Delivery::Accepted(text.to_string())),
        Some(("ERR", text)) => Ok(Delivery::Rejected(text.to_string())),
        _ if reply == "OK" => Ok(Delivery::Accepted(String::new())),
        _ => Ok(Delivery::Rejected("unexpected reply from instance".into())),
    }
}

/// Store a link for the next lmm start (no instance was running).
/// The file is user-only (0600): the link contains a download key.
pub fn spool(paths: &DataPaths, raw_link: &str) -> Result<PathBuf> {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let file = paths
        .spool_dir
        .join(format!("{nanos:020}-{}.nxm", std::process::id()));
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(&file)
        .map_err(|e| Error::io(&file, e))?;
    f.write_all(raw_link.as_bytes())
        .and_then(|()| f.write_all(b"\n"))
        .and_then(|()| f.sync_all())
        .map_err(|e| Error::io(&file, e))?;
    Ok(file)
}

/// Read and delete all spooled links, oldest first. Contents are returned
/// raw and must be validated by the caller; files that cannot be a request
/// (too large, unreadable) are removed and skipped.
pub fn drain_spool(paths: &DataPaths) -> Result<Vec<String>> {
    let mut entries: Vec<PathBuf> = match std::fs::read_dir(&paths.spool_dir) {
        Ok(rd) => rd
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|e| e == "nxm"))
            .collect(),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(e) => return Err(Error::io(&paths.spool_dir, e)),
    };
    entries.sort(); // names start with a zero-padded timestamp

    let mut links = Vec::new();
    for path in entries {
        let ok_size = std::fs::metadata(&path).is_ok_and(|m| m.len() <= MAX_SPOOL_FILE);
        if ok_size && let Ok(text) = std::fs::read_to_string(&path) {
            let line = text.trim();
            if !line.is_empty() {
                links.push(line.to_string());
            }
        }
        // Consumed (or garbage) either way; a spool file is processed once.
        let _ = std::fs::remove_file(&path);
    }
    Ok(links)
}

/// The receiving end, owned by the interactive shell.
pub struct NxmListener {
    listener: UnixListener,
    path: PathBuf,
}

impl NxmListener {
    /// Bind the per-data-dir socket. If another live instance already owns
    /// it, fail with [`Error::AlreadyListening`]; a dead socket file left by
    /// a crash is silently replaced.
    pub fn bind(paths: &DataPaths) -> Result<NxmListener> {
        let path = socket_path(paths);
        match UnixListener::bind(&path) {
            Ok(listener) => Ok(NxmListener { listener, path }),
            Err(e) if e.kind() == std::io::ErrorKind::AddrInUse => {
                // Is somebody actually home?
                match UnixStream::connect(&path) {
                    Ok(_) => Err(Error::AlreadyListening),
                    Err(_) => {
                        // Stale socket from a crashed instance: reclaim it.
                        std::fs::remove_file(&path).map_err(|err| Error::io(&path, err))?;
                        let listener =
                            UnixListener::bind(&path).map_err(|err| Error::io(&path, err))?;
                        Ok(NxmListener { listener, path })
                    }
                }
            }
            Err(e) => Err(Error::io(&path, e)),
        }
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Accept connections forever, one at a time (nxm clicks are rare and the
    /// per-connection work is tiny; serial handling keeps this trivial).
    ///
    /// `handler` gets the raw link text and returns Ok(ack) / Err(reason);
    /// the corresponding `OK`/`ERR` line is sent back. Handler input is
    /// untrusted and must be validated inside the handler.
    ///
    /// Runs on its own thread; it ends when the process does. Individual
    /// connection errors are swallowed — a misbehaving client must not be
    /// able to take the listener down.
    pub fn serve(&self, mut handler: impl FnMut(&str) -> std::result::Result<String, String>) {
        loop {
            self.serve_one(&mut handler);
        }
    }

    /// Accept and handle a single connection (blocking). Split out from
    /// [`Self::serve`] so tests can exercise the protocol without an
    /// infinite loop.
    pub fn serve_one(&self, mut handler: impl FnMut(&str) -> std::result::Result<String, String>) {
        let Ok((mut stream, _addr)) = self.listener.accept() else {
            return;
        };
        let _ = stream.set_read_timeout(Some(IO_TIMEOUT));
        let _ = stream.set_write_timeout(Some(IO_TIMEOUT));

        let mut line = String::new();
        if BufReader::new(&stream)
            .take(MAX_LINE)
            .read_line(&mut line)
            .is_err()
        {
            return;
        }
        let reply = match line.trim().strip_prefix("NXM ") {
            Some(raw_link) => match handler(raw_link) {
                Ok(ack) => format!("OK {ack}\n"),
                Err(reason) => format!("ERR {reason}\n"),
            },
            None => "ERR expected 'NXM <url>'\n".to_string(),
        };
        let _ = stream.write_all(reply.as_bytes());
    }
}

impl Drop for NxmListener {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.path);
    }
}

/// Restrict the spool dir to the owner; links inside carry download keys.
pub fn ensure_spool_private(paths: &DataPaths) -> Result<()> {
    let perms = std::fs::Permissions::from_mode(0o700);
    std::fs::set_permissions(&paths.spool_dir, perms).map_err(|e| Error::io(&paths.spool_dir, e))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_paths() -> (tempfile::TempDir, DataPaths) {
        let dir = tempfile::tempdir().unwrap();
        let paths = DataPaths::new(dir.path().to_path_buf(), None);
        paths.ensure_dirs().unwrap();
        (dir, paths)
    }

    #[test]
    fn spool_roundtrip() {
        let (_dir, paths) = test_paths();
        assert_eq!(drain_spool(&paths).unwrap(), Vec::<String>::new());
        spool(&paths, "nxm://skyrim/mods/1/files/2?key=k").unwrap();
        spool(&paths, "nxm://skyrim/mods/3/files/4").unwrap();
        let drained = drain_spool(&paths).unwrap();
        assert_eq!(
            drained,
            vec![
                "nxm://skyrim/mods/1/files/2?key=k".to_string(),
                "nxm://skyrim/mods/3/files/4".to_string(),
            ]
        );
        assert_eq!(
            drain_spool(&paths).unwrap(),
            Vec::<String>::new(),
            "consumed"
        );
    }

    #[test]
    fn spool_files_are_private() {
        let (_dir, paths) = test_paths();
        let file = spool(&paths, "nxm://skyrim/mods/1/files/2?key=secret").unwrap();
        let mode = std::fs::metadata(&file).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o600);
    }

    #[test]
    fn oversized_spool_files_are_discarded() {
        let (_dir, paths) = test_paths();
        let junk = paths.spool_dir.join("00-junk.nxm");
        std::fs::write(&junk, "x".repeat(MAX_SPOOL_FILE as usize + 1)).unwrap();
        assert_eq!(drain_spool(&paths).unwrap(), Vec::<String>::new());
        assert!(!junk.exists(), "junk is removed, not reprocessed forever");
    }

    #[test]
    fn send_reports_not_running() {
        // The socket name embeds a hash of this test's unique temp data dir,
        // so nothing can be listening on it.
        let (_dir, paths) = test_paths();
        match send_to_running(&paths, "nxm://skyrim/mods/1/files/2").unwrap() {
            Delivery::NotRunning => {}
            _ => panic!("nothing should be listening"),
        }
    }

    #[test]
    fn second_bind_on_live_socket_fails() {
        let (_dir, paths) = test_paths();
        let _listener = NxmListener::bind(&paths).unwrap();
        assert!(matches!(
            NxmListener::bind(&paths),
            Err(Error::AlreadyListening)
        ));
    }

    #[test]
    fn listener_accepts_link_and_replies() {
        let (_dir, paths) = test_paths();
        let listener = NxmListener::bind(&paths).unwrap();

        // Serve exactly one request on a helper thread, echoing via handler.
        let server = std::thread::spawn(move || {
            let mut got = None;
            listener.serve_one(|raw| {
                got = Some(raw.to_string());
                Ok("queued".into())
            });
            got
        });

        match send_to_running(&paths, "nxm://skyrim/mods/1/files/2?key=k").unwrap() {
            Delivery::Accepted(ack) => assert_eq!(ack, "queued"),
            _ => panic!("delivery should be accepted"),
        }
        let got = server.join().expect("server thread");
        assert_eq!(got.as_deref(), Some("nxm://skyrim/mods/1/files/2?key=k"));
    }

    #[test]
    fn garbage_request_gets_err_reply() {
        let (_dir, paths) = test_paths();
        let listener = NxmListener::bind(&paths).unwrap();
        let sock = listener.path().to_path_buf();
        let server = std::thread::spawn(move || listener.serve_one(|_| Ok(String::new())));

        let mut stream = UnixStream::connect(&sock).unwrap();
        stream.write_all(b"HELLO there\n").unwrap();
        let mut reply = String::new();
        BufReader::new(&stream).read_line(&mut reply).unwrap();
        assert!(reply.starts_with("ERR "), "{reply}");
        server.join().expect("server thread");
    }

    #[test]
    fn stale_socket_is_reclaimed_and_drop_cleans_up() {
        let (_dir, paths) = test_paths();
        let path = socket_path(&paths);
        // Simulate a crashed instance: a socket file nobody is serving.
        drop(UnixListener::bind(&path).unwrap());
        assert!(path.exists(), "stale socket file left behind");

        let listener = NxmListener::bind(&paths).expect("stale socket reclaimed");
        drop(listener);
        assert!(!path.exists(), "drop removes the socket file");
    }
}
